- name: "Install, run and collect sosreports"
  hosts: all
  remote_user: root
  gather_facts: off
  tasks:
    - name: "Register to Satellite"
      include_role:
        name: rhsm_helper
      vars:
        environment: Library
